In [3]:
%pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
lista = [1, 1.1, True, "hola", []]

In [6]:
type(lista)

list

In [7]:
len(lista)

5

In [9]:
# Dot-notation
np.array([1, 1.1, True, "hola"])

array(['1', '1.1', 'True', 'hola'], dtype='<U32')

In [10]:
arreglo = np.array([1, 2, 3, 4, 5])

In [11]:
type(arreglo)

numpy.ndarray

In [12]:
arreglo

array([1, 2, 3, 4, 5])

In [13]:
dir(arreglo)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [14]:
arreglo.shape

(5,)

In [15]:
arreglo.dtype

dtype('int64')

In [16]:
arreglo.size

5

In [17]:
matriz_python = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [18]:
type(matriz_python)

list

In [22]:
matriz_python[0][0]

1

In [23]:
matriz_python[1][1]

5

In [ ]:
# Fila columna
# fi-co
matriz_python[2][0]

7

In [26]:
matriz_python + matriz_python

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [27]:
dir(matriz_python)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [29]:
matriz_numpy = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [30]:
type(matriz_numpy)

numpy.ndarray

In [33]:
matriz_numpy[0, 0].item()

1

In [34]:
matriz_numpy.size

9

In [35]:
matriz_numpy.shape

(3, 3)

In [36]:
matriz_numpy.dtype

dtype('int64')

In [38]:
matriz_numpy + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [39]:
matriz_numpy * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [40]:
matriz_numpy + matriz_numpy

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [41]:
matriz_numpy - matriz_numpy

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
matriz_numpy.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
np.random.random()

0.28472170061742064

In [56]:
np.random.randint(20)

19

In [58]:
np.random.randint(20, size=(5, 3))

array([[16, 12, 17],
       [ 9, 19,  3],
       [ 2,  8, 17],
       [ 3,  9,  0],
       [ 8, 11,  0]])

In [59]:
np.random.seed(1996)

In [60]:
np.random.randint(20, size=(5, 3))

array([[ 1,  2,  3],
       [ 6,  9,  3],
       [15, 14, 11],
       [ 4,  2, 16],
       [ 5, 10, 19]])

In [61]:
np.random.randint(20, size=(5, 3))

array([[ 1, 12,  8],
       [ 6,  0, 19],
       [13, 12, 10],
       [ 7,  4,  6],
       [19,  5, 12]])

In [62]:
# Slicing en ndarray

matriz_numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
matriz_numpy[1, 1:]

array([5, 6])

In [66]:
matriz_grande = np.random.randint(1, 101, size=(10, 10))

In [68]:
matriz_grande

array([[ 42,  81,  72,  71,  53,  12,  24,  30,  94,  40],
       [ 11,  93,  97,   6,  88,  69,   2,   4,  12,  68],
       [ 21,  63,  16,  76,  60,  99,  49,   2,  17,  37],
       [ 55,  29,  46,  76,  45,  21,  54,  58,  64,  62],
       [ 35,  57,  56,  20,  69,   9,  31,  78,   6,  36],
       [ 35,  11,  46,  22,  57,  71,  82,  40,  17,  29],
       [ 92,  92,  71,  49,  40,  10,  68,  72,  32,  82],
       [ 15,  48,  65,  24,  55, 100,  59,  73,  57,  22],
       [ 37,  40,   5,   4,  41,  51,  67,  35,  21,  19],
       [ 12,  83,  30,  85,  92,  19,  73,  14,   5,  30]])

In [71]:
matriz_grande[3:6, 3:6]

array([[76, 45, 21],
       [20, 69,  9],
       [22, 57, 71]])